spring:
  cloud:
    gateway:
      routes:
        - id: r1
          predicates:
            - Path=/customers/**
          uri: http://localhost:8082/
        - id: r2
          uri: http://localhost:8084/
          predicates:
            - Path=/accounts/**
server:
  port: 8080